### ISSUE TITLE
Wishlist: Powering Mode - function already exists

### ISSUE THREAD

**Issue by telephasicworkshop** [davidem/UPS-Lite#1]
Saw this on your wishlist, but the original code by linshuqin329 already had this capability.

The manual, even though only in Chinese: [](url)https://github.com/linshuqin329/UPS-Lite/blob/master/UPS-Lite%20V1.2%20%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E.pdf

After you jump 2 solder pads, you can read if the UPS is Plugged or Unplugged.

`import RPi.GPIO as GPIO`

`GPIO.setmode(GPIO.BCM)`
`GPIO.setwarnings(False)`
`GPIO.setup(4,GPIO.IN)`

`if (GPIO.input(4) == GPIO.HIGH):`
`     print "Power Adapter Plug In "`
`if (GPIO.input(4) == GPIO.LOW):`
`     print "Power Adapter Unplug"`

**Comment by davidem** [comment]
Sorry for the late response, I just noticed this now. Not sure why I wasn't triggered before :) 

Thanks for the info! I'll definately have a look

**Comment by davidem** [comment]
Ah, now I see. Linshuqin329 has updated his script in the beginning of this year. I'll check his changes later this week when I have more time 👍

**Comment by telephasicworkshop** [comment]
Haha no problem :smiley:
In the meantime he also added an English version of his instruction manual.
Good luck! :thumbsup:

**Comment by davidem** [comment]
I've found my zero and finally had time to update the script. It now uses RPi.GPIO to check if it is powered by battery or power adapter. 

Thanks again for pointing this out to me 👍
